name: Sanjay Rohila
markdown: redcarpet
highlighter: rouge
timezone: Asia/Kolkata
baseurl: ""
url: "http://crazyrohila.github.io"
permalink: /articles/:title
include: ['.htaccess']
keep_files: ['.git']
markdown_ext: "markdown,mkdown,mkdn,mkd,md,txt"
# Main Navigation links
navigation:
  - title: About me
    url: /about/
    text: About
  - title: Demos
    url: http://crazyrohila.github.io/work/
    text: Code
  - title: Articles
    url: /articles/
    text: Blog
